name: sample service build and deploy
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master


env:
  IMAGE_NAME: ghcr.io/jasondewitt/sample-service
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-app:
    name: build-app
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: set up variables
        run: |
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "DEPLOY_BUCKET=storycorps-elasticbeanstalk-deploy" >> $GITHUB_ENV
          echo "EB_APP_NAME=storycorps_archive" >> $GITHUB_ENV
          echo "ECR_REGION=us-west-2" >> $GITHUB_ENV
      - name: set version tag var
        run: |
          echo "VERSION_TAG=$(echo ${BRANCH}-${GITHUB_RUN_ID})" >> $GITHUB_ENV

      - name: checkout repo
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: test image tag variable
        run: echo "$IMAGE_NAME:$VERSION_TAG"

      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }}
          context: .
          file: ./Dockerfile



